framework: mocha
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./node-tests/blueprints/*.js"
    - "./packages/ember/tests/reexports_test.js"
postMerge:
  pattern: 
    - "./node-tests/blueprints/*.js"
    - "./packages/ember/tests/reexports_test.js"
postRun:
     command:
        - yarn --version
configFile: "bin/run-tests.js"
version: 1.0
