framework: mocha
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./node-tests/blueprints/*.js"
    - "./bin/run-tests.js"
postMerge:
  pattern: 
    - "./node-tests/blueprints/*.js"
    - "./bin/run-tests.js"
postRun:
     command:
        - yarn --version
version: 1.0
