---
postMerge:
  preRun:
    command:
      - yarn install
  subModules:          #Not to be changed
    - name: blueprints-js      
      path : "./"
      pattern: 
        - "./node-tests/blueprints/**/*-test.js"
      framework : mocha      
      postRun:
        command:
          - node --version
        
    - name: blueprints-ts      
      path : "./"
      pattern: 
        - "./node-tests/blueprints/**/*-test.js"
        
      framework : mocha
      runPreRunEveryTime: true
      preRun:
        env:
          EMBER_TYPESCRIPT_BLUEPRINTS: true
        command:
          - node --version
            
      postRun:
        command:
          - node --version
      
        
      
        
preMerge :  
  subModules:          #Not to be changed
    - name: blueprints-js      
      path : "./"
      pattern: 
        - "./node-tests/blueprints/**/*-test.js"
      framework : mocha      
      postRun:
        command:
          - node --version
        
    - name: blueprints-ts      
      path : "./"
      pattern: 
        - "./node-tests/blueprints/**/*-test.js"
        
      framework : mocha
      runPreRunEveryTime: true
      preRun:
        env:
          EMBER_TYPESCRIPT_BLUEPRINTS: true
        command:
          - node --version
            
     
        
  
parallelism: 2 # this will be depricated in future
version : 2.0

