framework: mocha
preRun:
     command:
        - yarn install
        - yarn run build
preMerge:
  pattern:
    - "./node-tests/blueprints/*.js"
postMerge:
  pattern: 
    - "./node-tests/blueprints/*.js"
postRun:
     command:
        - yarn --version
version: 1.0
