framework: mocha
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./node-tests/blueprints/*.js"
#     - "./packages/ember/tests/**/*_test.js"
postMerge:
  pattern: 
    - "./node-tests/blueprints/*.js"
#     - "./packages/ember/tests/**/*_test.js"
postRun:
     command:
        - yarn --version
version: 1.0
